name: artenc-test
favicon: null
layout_spectrum: 1
typography_spectrum: 0.34944
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#024f79'
    - '#5f061c'
    - '#e3aa8c'
    - '#dd0016'
  brandStrength: 0.75
  lightness: 0.625
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
